### ISSUE TITLE
AI prompt set to 100 characters or less? Or broken GUI?

### ISSUE THREAD

**Issue by wbste** [karakeep-app/karakeep#623]
### Describe the Bug

I must be missing something. I started with the default text prompt, and tweaked it slightly. When I try to add it, it says I'm limited to 100 characters or less. Is that right?
The default one is 700+

I feel like the GUI isn't working quite right, as I would imagine the lower text would be editable. Maybe that 100 characters is for a title? But then I don't see where to actually enter my own text; the textboxes below are not editable.

It's also only a text field that is one line tall; it can't be resized vertically.

Error is: String must contain at most 100 character(s)

### Steps to Reproduce

Try to add a custom AI prompt

### Expected Behaviour

You can add one around the same size as the default one.

### Device Details

Firefox and Chrome

### Exact Hoarder Version

v0.18.0

**Comment by MohamedBassem** [comment]
The idea is that you add multiple rules which translate to one per line. But I do acknowledge that 100 chars per rule is still not much and I'll increase it in the next release.

**Comment by MohamedBassem** [comment]
just to be clear. The rules that you add don't replace the original prompts, you're basically just adding more rules to the default prompt
