### ISSUE TITLE
youtube volume

### ISSUE THREAD

**Issue by gilbrotheraway** [karakeep-app/karakeep#636]
### Describe the feature you'd like

which volume are youtube videos downloaded to? i'd like them to be stored on the HDD but not sure how hoarder volumes work

### Describe the benefits this would bring to existing Hoarder users

?

### Can the goal of this request already be achieved via other means?

?

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

**Comment by MohamedBassem** [comment]
All assets (images, video, pdfs) are in `<DATA_DIR>/assets`. We can probably introduce a new `ASSETS_DIR` env variable to customize it if needed.

**Comment by MohamedBassem** [comment]
According to your compose file it's:

${PATH_TO_APPDATA}/hoarder/config

**Comment by MohamedBassem** [comment]
@Fuckingnameless no, the services don't need to run as root. I'll fix that in the context of #606

**Comment by MohamedBassem** [comment]
Anything left for this issue or should we close it?
